version: "3.7"

services:
  runme:
    image: pi-k3s-steup
    build:
      context: .
      dockerfile: dockerfile
    environment:
      env_file: .env
    volumes:
      - type: volume
        source: homedir
        target: /root

volumes:
  homedir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker-data/home
