version: "3.7"

services:
  runme:
    image: pi-k3s-steup
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    volumes:
      - ./.docker-data/home:/root
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - ${dns_server}
    networks:
      - pic

networks:
  pic:
    driver: bridge
