version: "3.7"

services:
  runme:
    image: pi-k3s-steup
    build:
      context: .
      dockerfile: dockerfile
    environment:
      env_file: .env
    volumes:
      - ./.docker-data/home:/root
