version: "3.7"

# pulling some info from - https://github.com/k3s-io/k3s/blob/master/docker-compose.yml
services:
  runme:
    image: pi-k3s-setup
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    privileged: true
    volumes:
      - ./.docker-data/.ssh:${ID_RSA_PUB_LOCATION:-/root/.ssh}
      - ./.docker-data/.kube:/.kube
    network_mode: host
